repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: check-symlinks
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
