repos:
  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: check-symlinks
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/life4/flakehell
    rev: v.0.8.0
    hooks:
      - id: flakehell
        additional_dependencies: [
          flake8!=3.9.1,
          flake8-bandit,
          flake8-bugbear,
          flake8-builtins,
          flake8-comprehensions,
          flake8-docstrings,
          flake8-simplify,
          flake8-use-fstring,
          pep8-naming,
        ]
