[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core"]

[project]
authors = [
  {name = "Not at Name", email = "julien@drlazor.be"},
]
classifiers = [
  "Development Status :: 1 - Planning",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development",
]
dependencies = [
  "click",
  "Jinja2",
  "toml",
]
description = "incipyt is a command-line tool that bootstraps a python project."
maintainers = [
  {name = "Not at Name", email = "julien@drlazor.be"},
]
name = "incipyt"
readme = "README.md"
requires-python = ">=3.6"
version = "0.0.1"

[project.optional-dependencies]
dev = [
  "black",
  "build",
  "flake8",
  "flakehell",
  "flake8-bandit",
  "flake8-bugbear",
  "flake8-builtins",
  "flake8-comprehensions",
  "flake8-docstrings",
  "flake8-simplify",
  "flake8-use-fstring",
  "pep8-naming",
  "pre-commit",
]
doc = [
  "m2r",
  "sphinxcontrib-apidoc",
  "sphinx_rtd_theme",
]
# Fix combatibility with flake8 3.9.[1-2] as of writing
extended_default_ignore = []
test = [
  "pytest-cov",
]

[project.scripts]
incipyt = "incipyt.cli:main"

[project.urls]
documentation = "https://github.com/NotANameServer/incipyt/wiki"
homepage = "https://pypi.org/incipyt"
repository = "https://github.com/NotANameServer/incipyt"

[tool.flakehell]
exclude = [
  ".env",
  ".git",
]
# Fix combatibility with flake8 3.9.[1-2] as of writing
extended_default_ignore = []

[tool.flakehell.plugins]
flake8-bandit = ["+*", "-S404", "-S603"]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-docstrings = ["+*", "-D105", "-D107"]
flake8-simplify = ["+*"]
flake8-use-fstring = ["+*", "-FS003"]
pep8-naming = ["+*"]
pycodestyle = ["+*", "-W503", "-E501"]
pyflakes = ["+*"]

[tool.flakehell.exceptions."incipyt/*__init__.py"]
pyflakes = ["-F401"]

[tool.flakehell.exceptions."incipyt/_*/*.py"]
flake8-docstrings = ["-*"]

[tool.flakehell.exceptions."incipyt/__*__.py"]
flake8-docstrings = ["-D100", "-D104"]

[tool.flakehell.exceptions."incipyt/actions/*.py"]
flake8-docstrings = ["-D100"]

[tool.flakehell.exceptions."incipyt/cli.py"]
flake8-docstrings = ["-D103"]
