name: Dependabot on pre-commit hooks

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

on:
  schedule:
    - cron: 13 2 * * 0 # weekly

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-python@v4.5.0
        with:
          cache: pip
          cache-dependency-path: pyproject.toml
          check-latest: true
          python-version: 3.11
      - env:
          PIP_UPGRADE: True
          PIP_UPGRADE_STRATEGY: eager
        run: python -m pip install -e ".[dev]"
      - run: pre-commit autoupdate
      - id: cache-pre-commit
        uses: actions/cache@v3.3.1
        with:
          key: ${{ hashFiles('.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit
      - if: ${{ ! steps.cache-pre-commit.outputs.cache-hit }}
        run: pre-commit install-hooks
      - uses: peter-evans/create-pull-request@v4.2.4
        with:
          author: "GitHub <noreply@github.com>"
          base: ${{ github.ref_name }}
          branch: dependabot/pre-commit/${{ github.ref_name }}
          committer: "GitHub <noreply@github.com>"
          commit-message: "chore(dev): bump pre-commit hooks"
          labels: |
            dependencies
            pre-commit
          title: "chore(dev): bump pre-commit hooks"
