name: CI - Test package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install deps
      run: |
        python -m pip install --upgrade pip flit
        python -m flit install --deps develop
    - name: Check format with black
      run: python -m black --check incipyt
    - name: Lint with flakehell
      run: python -m flakehell lint incipyt

  test:
    name: Tests
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    env:
      _OS: ${{ matrix.os }}
      _PY: ${{ matrix.python-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      run: |
        python -m pip install --upgrade pip flit
        python -m flit install --deps develop
    - name: Run tests with pytest
      run: pytest --cov=./ --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        env_vars: _OS,_PY
